### ISSUE TITLE
invalid type: null, expected a boolean at line 1 column 4

### ISSUE THREAD

**Issue by santoshs** [Anush008/chromadb-rs#4]
When trying to upsert a document into chromadb, the upsert function returns the following error:

    .invalid type: null, expected a boolean at line 1 column 4

If I can read code right, in upsert function

    let response = response.json::<bool>()?;

assumes the response is a bool, but from the chromadb API reference, the response is of the following type:

```
{
  "detail": [
    {
      "loc": [
        "string",
        0
      ],
      "msg": "string",
      "type": "string"
    }
  ]
}
```
Though, the documents are upserted correctly into the DB.

I am using version 0.4.3 and chromadb from docker (version: 0.4.17).

**Comment by Anush008** [comment]
Appears to be a compatibility issue with the updated schema.
Thanks for opening an issue, I'll see to resolve this.

**Comment by Anush008** [comment]
Should be resolved.
https://github.com/Anush008/chromadb-rs/commit/96ddf2761ddd2bffa5ecf3f7a776442f04a0a97a
