### ISSUE TITLE
Support basic auth and API tokens

### ISSUE THREAD

**Issue by kevinji** [Anush008/chromadb-rs#6]
For [authentication](https://docs.trychroma.com/usage-guide#authentication), the client should offer the option to pass in headers for basic auth (`Authorization`) or for API tokens (`Authorization: Bearer` or `X-Chroma-Token`).

**Comment by Anush008** [comment]
Hi Kevin. Thanks for raising the issue. I am working this week. I could take a look at this during the weekend.

In the meantime, any contributions are welcome 🤗
