### ISSUE TITLE
[QUESTION] QueryResults Option's usage

### ISSUE THREAD

**Issue by fgsch** [Anush008/chromadb-rs#9]
QueryResults is defined as:

```
pub struct QueryResult {
    pub ids: Vec<Vec<String>>,
    pub metadatas: Option<Vec<Option<Vec<Option<Metadata>>>>>,
    pub documents: Option<Vec<Option<Vec<Option<String>>>>>,
    pub embeddings: Option<Vec<Option<Vec<Embedding>>>>,
    pub distances: Option<Vec<Option<Vec<f32>>>>,
}
```

Beyond the outer `Option` for all the fields and the innermost one for MetaData, why is the reason/purpose for the rest?
I've so far failed to create a query result where these are needed.

**Comment by Anush008** [comment]
Hi @fgsch. These structures are dated. They need an update.

I will look into this during the weekend.

**Comment by fgsch** [comment]
Thanks for letting me know. 

Would you be interested in a PR?

**Comment by Anush008** [comment]
@fgsch, contributions are always 🤗

**Comment by Anush008** [comment]
Closing since stale.
Please feel free to re-open if needed.
